# -*- coding: utf-8 -*-
"""crime_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XGGai7YMoI82SLlpt6aQ2vUBY_FV5sx4
"""

import pandas as pd
crime_data = pd.read_csv('crime_data.csv')

print("Features of the crime_data.csv:")
print(crime_data.columns)
print("\nStructure of the crime_data.csv:")
print(crime_data.info())
print("\nHead of the crime_data.csv:")
print(crime_data.head())
print("\nTail of the crime_data.csv:")
print(crime_data.tail())

# Display structure
print("\nStructure of the crime_data.csv:")
print(crime_data.info())

# Display head
print("\nHead of the crime_data.csv:")
print(crime_data.head())

# Convert 'Begin Date Of Occurrence' to datetime
import matplotlib.pyplot as plt

crime_data['Begin Date Of Occurrence'] = pd.to_datetime(crime_data['Begin Date Of Occurrence'])

# Set 'Begin Date Of Occurrence' as index
crime_data.set_index('Begin Date Of Occurrence', inplace=True)

# Resample data to monthly frequency and sum incidents
monthly_incidents = crime_data['Total Incidents'].resample('M').sum()

# Plot time series of total incidents
plt.figure(figsize=(12, 6))
plt.plot(monthly_incidents)
plt.title('Total Incidents Over Time')
plt.xlabel('Date')
plt.ylabel('Total Incidents')
plt.grid(True)
plt.show()

from statsmodels.tsa.seasonal import seasonal_decompose

# Decompose the time series
decomposition = seasonal_decompose(monthly_incidents, model='additive', period=12)

# Plot the decomposition
plt.figure(figsize=(12, 8))

# Original series
plt.subplot(411)
plt.plot(monthly_incidents, label='Original')
plt.legend(loc='upper left')

# Trend
plt.subplot(412)
plt.plot(decomposition.trend, label='Trend')
plt.legend(loc='upper left')

# Seasonal
plt.subplot(413)
plt.plot(decomposition.seasonal, label='Seasonal')
plt.legend(loc='upper left')

# Residual
plt.subplot(414)
plt.plot(decomposition.resid, label='Residual')
plt.legend(loc='upper left')

plt.tight_layout()
plt.show()

from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

# ACF plot
plt.figure(figsize=(12, 6))
plot_acf(monthly_incidents, lags=50, ax=plt.gca())
plt.title('Autocorrelation Function (ACF)')
plt.xlabel('Lag')
plt.ylabel('ACF')
plt.show()

# PACF plot
plt.figure(figsize=(12, 6))
plot_pacf(monthly_incidents, lags=50, ax=plt.gca())
plt.title('Partial Autocorrelation Function (PACF)')
plt.xlabel('Lag')
plt.ylabel('PACF')
plt.show()

from statsmodels.tsa.arima.model import ARIMA


model = ARIMA(monthly_incidents, order=(5,1,0))
results = model.fit()


forecast = results.predict(start=len(monthly_incidents), end=len(monthly_incidents) + 12, typ='levels')

plt.figure(figsize=(12, 6))
plt.plot(monthly_incidents, label='Original')
plt.plot(forecast, label='Forecast', linestyle='--')
plt.title('ARIMA Forecasting')
plt.xlabel('Date')
plt.ylabel('Total Incidents')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 6))
crime_data['Year'] = crime_data.index.year
total_incidents_by_year = crime_data.groupby('Year')['Total Incidents'].sum()
total_incidents_by_year.plot(kind='bar')
plt.title('Total Incidents by Year')
plt.xlabel('Year')
plt.ylabel('Total Incidents')
plt.xticks(rotation=45)
plt.grid(axis='y')
plt.show()

# Pie Chart - Distribution of Crime Categories
plt.figure(figsize=(8, 8))
crime_category_counts = crime_data['Crime Category'].value_counts()
plt.pie(crime_category_counts, labels=crime_category_counts.index, autopct='%1.1f%%', startangle=140)
plt.title('Distribution of Crime Categories')
plt.axis('equal')
plt.show()

import numpy as np

# Plot time series of total incidents with trend line
plt.figure(figsize=(12, 6))
plt.plot(monthly_incidents, label='Total Incidents')
plt.plot(monthly_incidents.rolling(window=12).mean(), color='red', linestyle='--', label='12-Month Rolling Mean')
plt.title('Total Incidents Over Time with Trend Line')
plt.xlabel('Date')
plt.ylabel('Total Incidents')
plt.legend()
plt.grid(True)
plt.show()

import seaborn as sns

# Select numerical columns for correlation matrix
numerical_columns = crime_data.select_dtypes(include='number')

# Calculate the correlation matrix
correlation_matrix = numerical_columns.corr()

# Plot the correlation matrix
plt.figure(figsize=(12, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix')
plt.show()

